name: Build Wheels

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            cibw_arch: x86_64
          - os: ubuntu-latest
            arch: aarch64
            cibw_arch: aarch64
          - os: windows-latest
            arch: x86_64
            cibw_arch: AMD64
          - os: windows-latest
            arch: aarch64
            cibw_arch: ARM64
          - os: macos-latest
            arch: x86_64
            cibw_arch: x86_64
          - os: macos-latest
            arch: aarch64
            cibw_arch: arm64
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-wheels
        with:
          python-version: ${{ inputs['python-version'] }}
          cibw-arch: ${{ matrix.cibw_arch }}
          artifact-name: wheels-${{ matrix.os }}-${{ matrix.arch }}
